/**
 * actionTypes
 */

export const GET_LIST = 'GET_LIST'
export const GET_LIST_SUCCESS = 'GET_LIST_SUCCESS'
export const GET_LIST_ERROR = 'GET_LIST_ERROR'
export const CLEAR_LIST = 'CLEAR_LIST'

export const GET_RECENT_ACTIVITY_LIST_TOP4 = 'GET_RECENT_ACTIVITY_LIST_TOP4'
export const GET_RECENT_ACTIVITY_LIST_TOP4_SUCCESS = 'GET_RECENT_ACTIVITY_LIST_TOP4_SUCCESS'

export const GET_RECENT_ACTIVITY_LIST = 'GET_RECENT_ACTIVITY_LIST'
export const GET_RECENT_ACTIVITY_LIST_SUCCESS = 'GET_RECENT_ACTIVITY_LIST_SUCCESS'

export const SERVICE_ERROR = 'SERVICE_ERROR'
