/**
 * actionTypes
 */

export const GET_LIST = 'GET_LIST'
export const GET_LIST_SUCCESS = 'GET_LIST_SUCCESS'
export const GET_LIST_ERROR = 'GET_LIST_ERROR'

export const GET_SCENICSPOT_LIST = 'GET_SCENICSPOT_LIST'
export const GET_RESTAURANT_LIST = 'GET_RESTAURANT_LIST'
export const GET_HOTEL_LIST = 'GET_HOTEL_LIST'
export const GET_ACTIVITY_LIST = 'GET_ACTIVITY_LIST'

export const GET_SCENICSPOT_LIST_SUCCESS = 'GET_SCENICSPOT_LIST_SUCCESS'
export const GET_RESTAURANT_LIST_SUCCESS = 'GET_RESTAURANT_LIST_SUCCESS'
export const GET_HOTEL_LIST_SUCCESS = 'GET_HOTEL_LIST_SUCCESS'
export const GET_ACTIVITY_LIST_SUCCESS = 'GET_ACTIVITY_LIST_SUCCESS'
