/**
 * actionTypes
 */

export const GET_SCENICSPOT_LIST_SUCCESS = 'GET_SCENICSPOT_LIST_SUCCESS'
export const GET_RESTAURANT_LIST_SUCCESS = 'GET_RESTAURANT_LIST_SUCCESS'
export const GET_HOTEL_LIST_SUCCESS = 'GET_HOTEL_LIST_SUCCESS'
export const GET_ACTIVITY_LIST_SUCCESS = 'GET_ACTIVITY_LIST_SUCCESS'


export const GET_LIST_FAIL = 'GET_LIST_FAIL'


